### ISSUE TITLE
hydra_etd app should use technical-metadata-service 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/technical-metadata-service#110]
Currently, hydra_etd creates technical metadata with jhove (see sul-dlss/hydra_etd/blob/master/app/controllers/parts_controller.rb#L27-L30).

We need code, in a branch, perhaps akin to https://github.com/sul-dlss/common-accessioning/tree/t575-techmd_service, to use the technical-metadata-service instead.

ticketed in this repo partly to get it on zenhub board.  See also sul-dlss/hydra_etd/issues/339

**Comment by jcoyne** [comment]
@ndushay I don't think there's anything to do here other than remove the manual generation in hydra_etd, right?

**Comment by ndushay** [comment]
does a call need to be made to tech-md-service to tell it to generate it?   

As i said above, this is partly ticketed here so it's on our zenhub board.

**Comment by jcoyne** [comment]
Technical metadata will be run when the item is accessioned, there's no need to manually trigger it.
