### ISSUE TITLE
[technical-metadata-service/stage] URI::InvalidURIError: bad URI(is not URI?): "file:///dor/workspace/dy/959/mr/6442/dy959mr6442/content/dy959mr6442_HOUSE 97 CMC part 3_sl.mp4"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/technical-metadata-service#116]
## Backtrace

    line 10 of [PROJECT_ROOT]/app/controllers/technical_metadata_controller.rb: block in create
    line 10 of [PROJECT_ROOT]/app/controllers/technical_metadata_controller.rb: map
    line 10 of [PROJECT_ROOT]/app/controllers/technical_metadata_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/68956/faults/62205755)

**Comment by andrewjbtw** [comment]
It looks like new techMD can't handle spaces in file names. I made an example to test that: https://argo-stage.stanford.edu/view/druid:gq295qr6999

The other HB errors for this are from my media content type testing. The files without spaces went through, but the files with spaces got stuck: https://argo-stage.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=media+testing
