### ISSUE TITLE
Technical metadata service needs to see Hydrus mount

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#122]
**Describe the bug**
Hydrus deposits store their files on the `/data/hydrus-files` mount. During accessioning, symlinks are created between `/data/hydrus-files` and the relevant `/dor` mount druid tree. 

The technical metadata service is failing on Hydrus deposits with errors like:

`technical-metadata : content dir not found for 'jh844xd7219.jpg' when searching '/dor/workspace/jh/844/xd/7219/jh844xd7219/content'`

The druid tree does exist for these objects in the /dor workspace, so it's likely that the techMD server does not have the Hydrus mount mounted.

**User Impact**
Hydrus items cannot be accessioned.

Hydrus items with this error: https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Hydrus&f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Atechnical-metadata%3Aerror

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss/operations-tasks/issues/2198

**Comment by andrewjbtw** [comment]
Mounts have been added and Hydrus deposits are working.
