### ISSUE TITLE
Error in technical-metadata service

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#123]
```
[technical-metadata-service/prod] JSON::ParserError: 434: unexpected token at 'FILE] /dor/workspace/zs/656/jt/4944/zs656jt4944/content/J_eps_LSL_2019.zip[ERROR] zip: not a valid zip file{"siegfried":"1.8.0","scandate":"2020-04-01T04:00:05-07:00","signature":"default.sig","created":"2020-01-21T23:30:42+01:00","identifiers":[{"name":"pronom","details":"DROID_SignatureFile_V96.xml; container-signature-20200121.xml"}],"files":[{"filename":"/dor/workspace/zs/656/jt/4944/zs656jt4944/content/J_eps_LSL_2019.zi...
```
## Backtrace

    line 37 of [PROJECT_ROOT]/app/services/file_identifier_service.rb: extract_file_types
    line 17 of [PROJECT_ROOT]/app/services/file_identifier_service.rb: identify
    line 80 of [PROJECT_ROOT]/app/services/technical_metadata_generator.rb: generate_metadata

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/68956/faults/62417641)

**Comment by justinlittman** [comment]
@peetucket Why was this re-opened?

**Comment by peetucket** [comment]
probably a mistake, didn't realize it was closed

**Comment by peetucket** [comment]
Actually, I think what happened is I edited the title and put the title in the body (to make it less obnoxious when viewed on the Zenboard) and then I closed the ticket by mistake instead of just closing the window.  So I re-opened it.  So I am not sure what the correct status should really be.
