### ISSUE TITLE
Prevent technical metadata from being a bottleneck

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#129]
It looks like once deposits reach a large enough scale, technical metadata becomes a bottleneck. All of these Google Books items waiting at "remediate-object" are running through technical metadata.

![techmd-gb](https://user-images.githubusercontent.com/8975583/78747747-03a03700-791f-11ea-8335-9df21ee9b171.png)

When accessioning a small number of books, technical metadata only appears to take 2-5 minutes (based on my non-scientific observations). It looks like it can take an hour or more when many books are being deposited at once.

**Comment by justinlittman** [comment]
New server requested in https://github.com/sul-dlss/operations-tasks/issues/2208

**Comment by andrewjbtw** [comment]
Developments:

1. New server deployed.
2. Prioritization implemented to keep Google Books from stopping other items.
