### ISSUE TITLE
Exception in technical metadata service in prod in time parsing

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/technical-metadata-service#131]
[technical-metadata-service/prod] ArgumentError: invalid date or strptime format - `2014:02:19 09:19:31+0000' `%Y-%m-%d %H:%M:%S%z'

## Backtrace

    line 132 of [PROJECT_ROOT]/app/services/av_characterizer_service.rb: to_iso_time
    line 71 of [PROJECT_ROOT]/app/services/av_characterizer_service.rb: block in extract_general
    line 61 of [PROJECT_ROOT]/app/services/av_characterizer_service.rb: tap

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/68956/faults/62761741)

**Comment by peetucket** [comment]
Looks like some dates are coming in with dates having colons unexpectedly instead of dashes, messing up the parsing.  Could deal by just blindly replacing all colons with dashes and parsing that way:

```
Time.strptime("#{time.gsub(':','-')}+0000", '%Y-%m-%d %H-%M-%S%z')
```
