### ISSUE TITLE
[technical-metadata-service/prod] ActiveRecord::StatementInvalid: PG::UntranslatableCharacter: ERROR:  unsupported Unicode escape sequence
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: {"creator":"Canon iR-ADV C5250  PDF","producer":...

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#151]
## Backtrace

    line 146 of [PROJECT_ROOT]/app/services/technical_metadata_generator.rb: upsert_dro_file
    line 43 of [PROJECT_ROOT]/app/services/technical_metadata_generator.rb: block (2 levels) in generate
    line 42 of [PROJECT_ROOT]/app/services/technical_metadata_generator.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/68956/faults/63551545)

**Comment by andrewjbtw** [comment]
This turns out to be stalling a Hydrus deposit. (The author just emailed us.)
