### ISSUE TITLE
Make it possible to add a single file, without re-calculating techmd for other files.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/technical-metadata-service#192]
I believe that we currently delete metadata for all files that are not provided.  We need to change this such that deletes are explicit.

**Comment by justinlittman** [comment]
Why?

**Comment by jcoyne** [comment]
I don't recall, this was 2 years ago. I'm happy to delete this ticket.

**Comment by justinlittman** [comment]
Some additional questions for consideration before moving to ready:
What is the problem that this ticket is attempting to address? Why does @andrewjbtw still desire this? How/what would invoke it?

Currently generation is skipped for any file that has techmd and has not changed: https://github.com/sul-dlss/technical-metadata-service/blob/main/app/services/technical_metadata_generator.rb#L66. Is that what this ticket is asking for or something different?

**Comment by andrewjbtw** [comment]
I think there was a misunderstanding because I don't remember discussing this ticket.

**Comment by ndushay** [comment]
none of us know what this means anymore.  closing.
