### ISSUE TITLE
workflow_service log on technical-metadata-service is complaining it can't be created, but it is there

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/technical-metadata-service#229]
See https://app.honeybadger.io/projects/68956/faults/74870729

Noticed the workflow_service.log  not found alerting a lot again on dor-techmd-prod... the log file existed but was timestamped from several weeks ago and was 0 bytes, trashed it, re-created, and then restarted the app and it seems to have slowed down but it still happening ... has been looked at previously by John and Naomi but it still happening

**Comment by peetucket** [comment]
Note it appears that the log file is not actually stored in the log folder, see https://github.com/sul-dlss/dor-workflow-client/blob/main/lib/dor/workflow/client.rb#L93

Noted, that there is a timestamped file corresponding with the deploy time at the root of the tech-md service

**Comment by peetucket** [comment]
The log file in the root of the app folder is being created, but it never seems to be added to (which corresponds with the cient erroring out).  Perhaps the dor-workflow-client does not have access to the write to a log file at the root of the rails app?

**Comment by peetucket** [comment]
Maybe every time a new client is created at https://github.com/sul-dlss/technical-metadata-service/blob/main/app/jobs/technical_metadata_workflow_job.rb#L41 it is trying to get a handle on the locked workflow_service.log file?

**Comment by peetucket** [comment]
looks like it was fixed by #230

**Comment by peetucket** [comment]
still seems to be happening, even though we should not be letting the dor:workflow:client create the logger anymore -- stumped

**Comment by peetucket** [comment]
big mystery -- and not occurring on stage or qa, so confusing

**Comment by mjgiarlo** [comment]
@peetucket A few workers from a month ago, not attached to the others, were running until a few moments ago, which may explain why #230 didn't fix things. I stopped them and restarted the pool. I *assume* this means your PR did fix things, and as such I am closing this issue again and resolving the exception. Let's see how long this lasts!

**Comment by peetucket** [comment]
WOOT
