### ISSUE TITLE
Add a service to show the techmd for a particular file.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/technical-metadata-service#33]
This could key off md5 of the file.

**Comment by justinlittman** [comment]
@jcoyne Can you provide some context of what / how this would be used? Should it also support druid / filename? All of the files for a druid?

**Comment by jcoyne** [comment]
I don't know yet. Presumably by argo or an indexing service so that we can display the tech metadata.  note, this is in the backlog.

**Comment by justinlittman** [comment]
closing in favor of #57
