### ISSUE TITLE
Identify WARC files as WARCs, not zips

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#343]
The technical metadata service is identifying WARC files as application/gzip. This is not wrong - in that the files are gzipped - but it would be better from a repository management perspective if they were identified as WARCs. 

I'm not sure what the path would be to achieve that, given this is coming from the output of the Siegfried file identification tool. In the structural metadata, these items are being identified as application/warc, but I think that's because they're being processed by a special "metadataExtractor.jar" file in the wasCrawlPreassemblyWF.

**Comment by mjgiarlo** [comment]
Investigate how to do this given tool limitations above.

**Comment by jcoyne** [comment]
@andrewjbtw I don't see any way to get around this limitation, because we have gzipped the warc file, which makes it a gzip archive. It would be incorrect to say the mimetype is something else.

**Comment by andrewjbtw** [comment]
There are some ambiguous file types: docx, xlsx, etc. are both zips and specific Microsoft file formats. Some tools identify them as the Microsoft type and some just as zip. Similar things happen with some Apple file bundles. I thought maybe someone had built a WARC id signature to address the same type of problem.

On the other hand, this may be better handled with possible enhancements (that I've been thinking about) to be able to record what's inside zips. We don't have a good handle on the contents of our data self-deposits because so many are zipped. I haven't ticketed any of that because I want to see how other repositories are handling the see-inside-a-zip problem.

**Comment by jcoyne** [comment]
I don't think there's a risk, to doing something like this, but just that it's not something that we can handle with siegfried, because in this case siegfried is doing it's job correctly.  If you want, we could add a procedure to look for gzip files, then uncompress them and then run siegfried again. I'm just not sure that's what is being asked here.

**Comment by mjgiarlo** [comment]
I have a working solution in https://github.com/sul-dlss/technical-metadata-service/pull/361 that I welcome thoughts on, @jcoyne @justinlittman
