### ISSUE TITLE
identify druids for objects not in tech-md-service db.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/technical-metadata-service#348]
This might utilize similar logic to PR sul-dlss/dor-services-app/pull/4079;  essentially, do a query to get all the druids in SDR (to Solr once Solr has all the druids?  or from the dor-services-app db?), and then do a query to get all the druids in tech-md-service, and do a diff.   Keep the list the druids as an artifact, and share the total number of objects not in tech-md-service.

**Comment by justinlittman** [comment]
[druids.txt.zip](https://github.com/sul-dlss/technical-metadata-service/files/8854025/druids.txt.zip)
Attached is the the list of the 1.7 million items that are in pres cat, but are not in techmd. It was generated with:
```
psql -h preservation-catalog-db-prod-01.stanford.edu -U pres -c "select concat('druid:', druid) from preserved_objects order by druid;" -t > druids.txt
scp pres@preservation-catalog-web-prod-01.stanford.edu:/opt/app/pres/preservation_catalog/current/druids.txt druids.txt
sort druids.txt > druids.pres.txt

psql -U techmd -c "select distinct druid from dro_files order by druid;" -t > druids.txt
scp techmd@dor-techmd-prod-a.stanford.edu:/opt/app/techmd/dor_techmd/current/druids.txt druids.txt
sort druids.txt > druids.techmd.txt

comm -23 druids.pres.txt druids.techmd.txt > druids.txt
```
