### ISSUE TITLE
Consider integrating with preservation / preservation storage

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#37]
Consider integrating with preservation / preservation storage rather than accessioning / dor workspace.

Motivation: Allow easier reprocessing of files.

One can imagine the following scenarios:
* Adding a new field to the model for a file type and wanting to reprocess existing files of that type to populate that field.
* Adding a new tool and wanting to reprocess existing files for the file types that the tool supports.
* Upgrading an existing tool and wanting to reprocess the files processed by previous versions of the tool (especially if there was a bug in earlier versions).

Currently, techmd processing is performed in the dor workspace as part of accessioning. Reprocessing files would require re-staging files, which is an expensive operation (and I don't believe is automated?).

What if we ran techmd processing against the preservation workspace? That way, we would always have access to files and could easily satisfy the scenarios above.

The preservation storage systems could be mounted read-only to avoid risk to the files.

**Comment by justinlittman** [comment]
Alternatively, it might just be enough to mount the preservation storage systems read-only and leave the workflows as is.

When wanting to re-process an existing item, the files on the preservation storage system would be used (performing whatever moab math is necessary to find the files).

**Comment by jcoyne** [comment]
Adoped by #71
