### ISSUE TITLE
technical_metadata_workflow_job should update workflow service on failure

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/technical-metadata-service#389]
If there is a failure like this in the job: https://app.honeybadger.io/projects/68956/faults/68877771

Then the workflow will complain that the workflow hasn't been updated in > 24 hours https://app.honeybadger.io/projects/58890/faults/64252829

It would be more clear if the job, when encountering an error, could update the status in the workflow service.  We'd want to consider that just becauase tech-md has failed, it will get retried via Sidekiq.

**Comment by andrewjbtw** [comment]
I was just about to file a ticket for this but I see there already is one. There are 3 tecmd jobs currently with errors that are just retrying repeatedly and not reporting back to the workflow service.
