### ISSUE TITLE
Add nagios monitoring

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#39]
After okcomputer is set up and deployed, work with ops to have nagios do appropriate checks of stage and prod machines.

**Comment by mjgiarlo** [comment]
Moving to backlog for now, since it is blocked.

**Comment by jermnelson** [comment]
Create Ops-Tasks: https://github.com/sul-dlss/operations-tasks/issues/2175 to add monitoring.

**Comment by mjgiarlo** [comment]
@jermnelson What's the status of this ticket? I don't see Nagios/OKComputer set up (in puppet) for the technical metadata service. The ops-tasks ticket above appears to be for the GBooks app, not techmd.

**Comment by jermnelson** [comment]
@mjgiarlo I went ahead and created a ticket for nagios tech-metadata here https://github.com/sul-dlss/operations-tasks/issues/2210. Not sure of the status for the Google Book's maybe it should be closed with the SLA being set to low.

**Comment by mjgiarlo** [comment]
@jermnelson agree. that one can be closed. thanks!
