### ISSUE TITLE
Restore support for brackets in filenames

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#437]
**Describe the bug**
@amyehodge and I were testing punctuation characters in file names and noticed that accessioning is stalling for files with brackets in filenames. Technical metadata gets stuck in retries with this error:

https://app.honeybadger.io/projects/68956/faults/87321260

Strangely, this is happening on prod but on stage I was able to accession a file with a bracket: https://argo-stage.stanford.edu/view/druid:cs058qy3439

This issue must be a regression because we've had a small number of deposits with brackets in filenames succeed over the years. Example: https://argo.stanford.edu/view/yy394gb6954

**User Impact**
Objects can't be accessioned - and possibly can't be updated - if a bracket is in the file name. It may not be common, but it does happen. We have both ETD and H2 deposits with brackets in at least one file name.

**To Reproduce**
1. https://argo.stanford.edu/view/druid:bm465rz3785 is currently in automated retries. But the error can be reproduced by accessioning an object where one of the files has a bracket in the name.

However, it may not be possible to reproduce this error on stage (see above for recent, working stage example).

**Expected behavior**
The system should accept a bracket in a filename.

**Additional context**
In stage, I saw that my test object hit an error at first and then eventually succeeded on retry. Since we load-balance techMD - I think - I wonder if the issue is at the server level, and one server on stage can parse brackets while the others can't.

**Comment by mjgiarlo** [comment]
@andrewjbtw This looks like it may be an error in the Siegfried 1.10.0 release (which prod is using but stage is not yet): https://github.com/richardlehane/siegfried/issues/227

A workaround is to change the techmd service so that it escapes filenames en route to siegfried. I'll make that change so we can test it.

**Comment by mjgiarlo** [comment]
@andrewjbtw I believe the fix in #441 is not the best one for changing this behavior. First, it's going to break when the next sf release is out. see https://github.com/richardlehane/siegfried/pull/229

Second, I overapplied the escaping to the three other characterization tools which causes them to break when filepaths contain e.g. spaces (and probably also brackets).

So I think what we should consider is reverting #441 and doing what we can to support the siegfried folks in getting a patch release out.

**Comment by andrewjbtw** [comment]
Confirming this is now fixed via a Siegfried update. A streaming video successfully accessioned with brackets in the filename, got technical metadata extracted, and also streams correctly in the viewer.
