### ISSUE TITLE
technical-metadata step is throwing file "not found" errors when an item contains duplicate files

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#485]
**Describe the bug**
The technical-metadata step generates technical metadata when files are accessioned. We recently changed the step to handle the "targeted file update" scenario when an update contain only new or modified files. Previously, the step always expected every file listed in the cocina to be present in the accessioning workspace.

Recently, a set of items that were versioned to add caption files hit errors at the technical metadata step.
https://argo.stanford.edu/catalog?f%5Bcollection_title_ssim%5D%5B%5D=Kogu+me+lugu%3A+digital+video+interviews%2C+2014&f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Atechnical-metadata%3Aerror

The updates to these items did not involve changing any JP2 files, so the techMD robot should have ignored those files. But the technical metadata errors indicate that the techMD robot was expecting to find at least one JP2 file in each item because those are the files reported as not found. 

I did some inspection and I think I see the problem: when a druid contains duplicate files, only one of those duplicates is stored in the Moab. The additional copies are referenced in Moab manifest metadata, which also stores the filenames of each copy of the identical file. So only one copy of the file is stored on disk, and that file has a particular filename that may differ from the filename for the other copies.

It looks like the techMD robot is hitting errors on specifically the duplicate files that are not stored in the Moab. In each of the druids that has an error, the same thumbnail image was used for each video stream within that druid. That means that only one of those JP2 files is stored in the Moab and the other copy is listed in the Moab metadata only. 

What might be happening is that the techMD robot sees the duplicate files - the ones that are not on disk in preservation - as new files that need techMD. This might be related to how we retrospectively generated techMD for old items. That process generated metadata for the files on disk in preservation and may not have accounted for the way Moabs handle duplicate files and their filenames. 

**User Impact**
It is holding up reaccessioning on items that contain duplicate files.

**To Reproduce**
1. Run Preassembly to update an existing item that contains duplicate files
2. See the error at the techMD step.

**Expected behavior**
techMD should not need to run on files that are already stored in the repository.

**Screenshots**

**Additional context**
It's possible this will also be a problem for items where files have been renamed without changes to content. That's also a case where Moab leaves the file alone on disk and just records the change in metadata.

It's possible that the "right" approach is going to be to do some technical-metadata regeneration to account for the complexity of how Moab handles filenames. It looks like we're in a situation where:

- techMD has been generated for all (or nearly all) files on disk in preservation
- techMD has not been generated for all **filenames** stored in Cocina/Moab metadata.

**Comment by justinlittman** [comment]
I think the problem is more simple: The TechMD robot was telling TechMD service to generate techmd for every preserved file. It was not skipping files that were not in the workspace (because they hadn't changed).

The only case the existing code handled was when no files existed in the workspace, in which case it treated as metadata only.
