### ISSUE TITLE
technical-metadata goes missing for existing files when new files are accessioned via targeted file updates

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#510]
**Describe the bug**
When an item is updated using "targeted file updates" - where only new or updated files are accessioned - the technical metadata for the existing, non-updated, files does not appear to be retained in the technical metadata service.

Take the following sequence:

1. Item is accessioned with 4 files.
2. Item is updated by adding 2 files.

The technical metadata for this item should now show information for all 6 files. But it appears that only the technical metadata for the two files that were added is retained.

Examples: 

1. In production, this item was originally accessioned without captions: https://argo.stanford.edu/view/bd699ky6829 Later, we added caption and transcript files. Currently, the technical metadata shown in Argo contains information about only the caption and transcript files:
>
<img width="478" alt="Screenshot 2024-02-20 at 3 07 10 PM" src="https://github.com/sul-dlss/technical-metadata-service/assets/8975583/8e93ec07-a4d8-4d01-8d8e-890e603d5154">

2. In stage, I demo'd how to use Preassembly to add files to an existing item, using this druid: https://argo-stage.stanford.edu/view/druid:fd184kw9975 After I added a single file "addition.tif", the technical metadata now consists of only metadata about that added file:
>
<img width="478" alt="Screenshot 2024-02-20 at 3 09 22 PM" src="https://github.com/sul-dlss/technical-metadata-service/assets/8975583/2ce61320-a8f8-4def-bfae-1380f7fe7722">
 
**User Impact**
Losing the technical metadata already generated for existing files means that we cannot accurately view or report on technical metadata. For example, I uncovered this issue while trying to generate a list of the durations of video files as part of the planning and analysis we're doing on captioning media.

We will need to regenerate technical metadata for all items that contain files for which we (no longer) have technical metadata.

**To Reproduce**
1. Accession an item on stage
4. Add a file to that item using the "targeted file update" method.
5. View the item in Argo
6. See that the technical metadata only contains information about the added file.

**Expected behavior**
When updating the items, the technical metadata for files that are left unchanged should not be discarded.

**Additional context**
I'm not sure how the technical metadata database is structured, so I'm not sure if the technical metadata for existing files is being "lost" or if it's still in the database but no longer considered part of the item's current version. If the metadata is in the database, then we may not need to regenerate it.

The ultimate goal is that for any item in Argo, the technical metadata display for that item should include all files in the current version of that item.

**Comment by ndushay** [comment]
Andrew, Aaron and I met on Wed Feb 21 to discuss this ticket.  We think there are 2-3 areas of work to resolve this problem.  

Part 1:  ensure the techmd-service database, when called by accessionWF 'technical-metadata' step by common-accessioning, ensures that all the files present in the current cocina structural metadata are present in the technical-metadata service database.   That is:  the technical-metadata step will send over all files for the object, or a subset of object files (for a targeted file update), and it will ensure the tech-md database has the information for all the current files in the cocina object, updating them as needed.

NOTE:  we're not sure how file deletions are handled.  Andrew will create or use a small object in stage or qa and then do a targeted update to a file, a target file add, and a targeted file delete;  Naomi will capture the logs to understand the params sent from the technical-metadata robot to the technical-metadata service.   And/or Andrew will show Naomi how to do these things.   Based on the findings, there may be a Part 2.

Part 2:  if necessary, make changes to ensure that targeted file deletions are handled properly in the technical metadata service (removed from the tech-md service database).

Part 3:  Determine which objects in the tech-metadata service database need remediation**, possibly with Andrew's help.   Set up a way to do this remediation.   This ticket may or may not be informative if massive amounts of remediation are needed:  #349.   Note:  set rolling indexer parallel processes in DSA  to 2 or 1 (not 3) parallel processes while this remediation is happening.

** ideas for this so far included:
- determine the date the tech-md service started getting targeted file updates;  any objects updated since then need to be checked/updated
- check all cocina objects to see if files in structural metadata match files in tech-md database, and update when they don't match
- ditto, but only check for number of files matching
- run a tech metadata update for all cocina (esp. if determining the subset of objects will take a lot of resource)

**Comment by andrewjbtw** [comment]
I've made three sample druids in stage. Each has gone through a different kind of versioning activity:

Adding a new file: https://argo-stage.stanford.edu/view/druid:cg145tv3602
- newfile.csv is new and it's the only file now with visible techMD

Modifying an existing file: https://argo-stage.stanford.edu/view/druid:sq061kj3924
- hopkins_vandevere_census_cards_lovers_point_0001.tif  was modified and is now the only file with visible techMD

Removing a file: https://argo-stage.stanford.edu/view/druid:tv188jw1364
- the PDF was removed but its techMD is still visible

**Comment by ndushay** [comment]
**Part 4:  Create an integration test**

We need an integration test that:
- creates an object with (2) files
- accessions it
- does a targeted file update to one file
- after v2 complete, confirms that argo page shows 2 files in content section and 2 files in technical metadata section.

**Comment by ndushay** [comment]
Logs from technical-metadata on stage:

### for cg145tv3602, which got newfile.csv last ###
```
production.log-20240223.gz:I, [2024-02-22T13:42:45.618101 #1847829]  INFO -- : [9d94ae40-839a-4fae-ada5-233a640885f4]   Parameters: {"druid"=>"druid:cg145tv3602", "files"=>[{"uri"=>"file:///dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", "md5"=>"d39b57350974ff87bb96a0cee6fd97bc"}, {"uri"=>"file:///dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"7bada0347599b6ef6fed075608670b1a"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/cg/145/tv/3602/cg145tv3602/content", "technical_metadatum"=>{"druid"=>"druid:cg145tv3602", "files"=>[{"uri"=>"file:///dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", "md5"=>"d39b57350974ff87bb96a0cee6fd97bc"}, {"uri"=>"file:///dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"7bada0347599b6ef6fed075608670b1a"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/cg/145/tv/3602/cg145tv3602/content"}}

# creating tech md for pdf and tif files
production.log-20240223.gz:I, [2024-02-22T13:42:45.623079 #1847829]  INFO -- : [9d94ae40-839a-4fae-ada5-233a640885f4] [ActiveJob] Enqueued TechnicalMetadataWorkflowJob (Job ID: 00c659ec-19a9-4f76-a0bf-63a02262a1a9) to Sidekiq(default) with arguments: {:druid=>"druid:cg145tv3602", :file_infos=>[#<FileInfo:0x00007f044edc1f78 @filepath="/dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", @md5="d39b57350974ff87bb96a0cee6fd97bc", @filename="hopkins_vandevere_census_cards_lovers_point_0001.pdf">, #<FileInfo:0x00007f044edc09e8 @filepath="/dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="7bada0347599b6ef6fed075608670b1a", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}
production.log-20240223.gz:I, [2024-02-22T13:42:45.623068 #1519085]  INFO -- : [ActiveJob] [TechnicalMetadataWorkflowJob] [00c659ec-19a9-4f76-a0bf-63a02262a1a9] Performing TechnicalMetadataWorkflowJob (Job ID: 00c659ec-19a9-4f76-a0bf-63a02262a1a9) from Sidekiq(default) enqueued at 2024-02-22T21:42:45Z with arguments: {:druid=>"druid:cg145tv3602", :file_infos=>[#<FileInfo:0x00007f2f94eaf130 @filepath="/dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", @md5="d39b57350974ff87bb96a0cee6fd97bc", @filename="hopkins_vandevere_census_cards_lovers_point_0001.pdf">, #<FileInfo:0x00007f2f94eaf0b8 @filepath="/dor/workspace/cg/145/tv/3602/cg145tv3602/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="7bada0347599b6ef6fed075608670b1a", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}

# creating tech md for csv file
production.log-20240223.gz:I, [2024-02-22T14:28:11.508976 #1847829]  INFO -- : [4e0c72cf-7673-40a6-90bc-a6bebc5b001b]   Parameters: {"druid"=>"druid:cg145tv3602", "files"=>[{"uri"=>"file:///dor/workspace/cg/145/tv/3602/cg145tv3602/content/newfile.csv", "md5"=>"cf68a0e40f714ef30014b4b0f1c76be8"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/cg/145/tv/3602/cg145tv3602/content", "technical_metadatum"=>{"druid"=>"druid:cg145tv3602", "files"=>[{"uri"=>"file:///dor/workspace/cg/145/tv/3602/cg145tv3602/content/newfile.csv", "md5"=>"cf68a0e40f714ef30014b4b0f1c76be8"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/cg/145/tv/3602/cg145tv3602/content"}}
production.log-20240223.gz:I, [2024-02-22T14:28:11.510237 #1847829]  INFO -- : [4e0c72cf-7673-40a6-90bc-a6bebc5b001b] [ActiveJob] Enqueued TechnicalMetadataWorkflowJob (Job ID: 2768f9c1-2dce-47a1-bdd7-37725d23a7a7) to Sidekiq(default) with arguments: {:druid=>"druid:cg145tv3602", :file_infos=>[#<FileInfo:0x00007f0451b95850 @filepath="/dor/workspace/cg/145/tv/3602/cg145tv3602/content/newfile.csv", @md5="cf68a0e40f714ef30014b4b0f1c76be8", @filename="newfile.csv">], :force=>false}

production.log-20240223.gz:I, [2024-02-22T14:28:11.512871 #1519079]  INFO -- : [ActiveJob] [TechnicalMetadataWorkflowJob] [2768f9c1-2dce-47a1-bdd7-37725d23a7a7] Performing TechnicalMetadataWorkflowJob (Job ID: 2768f9c1-2dce-47a1-bdd7-37725d23a7a7) from Sidekiq(default) enqueued at 2024-02-22T22:28:11Z with arguments: {:druid=>"druid:cg145tv3602", :file_infos=>[#<FileInfo:0x00007f45305dfb98 @filepath="/dor/workspace/cg/145/tv/3602/cg145tv3602/content/newfile.csv", @md5="cf68a0e40f714ef30014b4b0f1c76be8", @filename="newfile.csv">], :force=>false}
```

**Comment by ndushay** [comment]
### for sq061kj3924, which got a file modified: hopkins_vandevere_census_cards_lovers_point_0001.tif

```
production.log-20240223.gz:I, [2024-02-22T13:42:46.922967 #1847829]  INFO -- : [c9083a14-e5fe-4a10-81d4-12e71b47fa39]   Parameters: {"druid"=>"druid:sq061kj3924", "files"=>[{"uri"=>"file:///dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", "md5"=>"d39b57350974ff87bb96a0cee6fd97bc"}, {"uri"=>"file:///dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"7bada0347599b6ef6fed075608670b1a"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/sq/061/kj/3924/sq061kj3924/content", "technical_metadatum"=>{"druid"=>"druid:sq061kj3924", "files"=>[{"uri"=>"file:///dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", "md5"=>"d39b57350974ff87bb96a0cee6fd97bc"}, {"uri"=>"file:///dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"7bada0347599b6ef6fed075608670b1a"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/sq/061/kj/3924/sq061kj3924/content"}}
production.log-20240223.gz:I, [2024-02-22T13:42:46.926204 #1847829]  INFO -- : [c9083a14-e5fe-4a10-81d4-12e71b47fa39] [ActiveJob] Enqueued TechnicalMetadataWorkflowJob (Job ID: 60ed53d0-56a5-481b-be01-1f3e56894f96) to Sidekiq(default) with arguments: {:druid=>"druid:sq061kj3924", :file_infos=>[#<FileInfo:0x00007f044ede0d60 @filepath="/dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", @md5="d39b57350974ff87bb96a0cee6fd97bc", @filename="hopkins_vandevere_census_cards_lovers_point_0001.pdf">, #<FileInfo:0x00007f044ed8f7a8 @filepath="/dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="7bada0347599b6ef6fed075608670b1a", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}
production.log-20240223.gz:I, [2024-02-22T13:42:46.927245 #1519075]  INFO -- : [ActiveJob] [TechnicalMetadataWorkflowJob] [60ed53d0-56a5-481b-be01-1f3e56894f96] Performing TechnicalMetadataWorkflowJob (Job ID: 60ed53d0-56a5-481b-be01-1f3e56894f96) from Sidekiq(default) enqueued at 2024-02-22T21:42:46Z with arguments: {:druid=>"druid:sq061kj3924", :file_infos=>[#<FileInfo:0x00007f42aa7777e0 @filepath="/dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", @md5="d39b57350974ff87bb96a0cee6fd97bc", @filename="hopkins_vandevere_census_cards_lovers_point_0001.pdf">, #<FileInfo:0x00007f42aa777768 @filepath="/dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="7bada0347599b6ef6fed075608670b1a", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}
production.log-20240223.gz:I, [2024-02-22T13:56:19.563814 #1847829]  INFO -- : [70e1d74e-d3d1-41f9-a8e2-cf6eb8b4c66f] Started GET "/v1/technical-metadata/druid/druid:sq061kj3924" for 10.111.6.18 at 2024-02-22 13:56:19 -0800
production.log-20240223.gz:I, [2024-02-22T13:56:19.564923 #1847829]  INFO -- : [70e1d74e-d3d1-41f9-a8e2-cf6eb8b4c66f]   Parameters: {"druid"=>"druid:sq061kj3924"}
production.log-20240223.gz:I, [2024-02-22T14:28:12.961285 #1847829]  INFO -- : [bfe87d7c-aa93-442a-b12d-30d4d3c3ea00]   Parameters: {"druid"=>"druid:sq061kj3924", "files"=>[{"uri"=>"file:///dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"eb060c01628a8a941778576af59fa849"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/sq/061/kj/3924/sq061kj3924/content", "technical_metadatum"=>{"druid"=>"druid:sq061kj3924", "files"=>[{"uri"=>"file:///dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"eb060c01628a8a941778576af59fa849"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/sq/061/kj/3924/sq061kj3924/content"}}
production.log-20240223.gz:I, [2024-02-22T14:28:12.963716 #1519085]  INFO -- : [ActiveJob] [TechnicalMetadataWorkflowJob] [f9a8734c-3974-493d-b8c4-8d10f75ab8bf] Performing TechnicalMetadataWorkflowJob (Job ID: f9a8734c-3974-493d-b8c4-8d10f75ab8bf) from Sidekiq(default) enqueued at 2024-02-22T22:28:12Z with arguments: {:druid=>"druid:sq061kj3924", :file_infos=>[#<FileInfo:0x00007f2f93d73538 @filepath="/dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="eb060c01628a8a941778576af59fa849", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}
production.log-20240223.gz:I, [2024-02-22T14:28:12.963802 #1847829]  INFO -- : [bfe87d7c-aa93-442a-b12d-30d4d3c3ea00] [ActiveJob] Enqueued TechnicalMetadataWorkflowJob (Job ID: f9a8734c-3974-493d-b8c4-8d10f75ab8bf) to Sidekiq(default) with arguments: {:druid=>"druid:sq061kj3924", :file_infos=>[#<FileInfo:0x00007f04505e6810 @filepath="/dor/workspace/sq/061/kj/3924/sq061kj3924/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="eb060c01628a8a941778576af59fa849", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}
```

**Comment by ndushay** [comment]
### for tv188jw1364, which got the pdf file deleted
production.log-20240223.gz
```
# creating tech md for the file, first time
I, [2024-02-22T13:42:46.930484 #1847829]  INFO -- : [9dcf6b91-5833-4a73-9ffc-afa194fd54d0]   Parameters: {"druid"=>"druid:tv188jw1364", "files"=>[{"uri"=>"file:///dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", "md5"=>"d39b57350974ff87bb96a0cee6fd97bc"}, {"uri"=>"file:///dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"7bada0347599b6ef6fed075608670b1a"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/tv/188/jw/1364/tv188jw1364/content", "technical_metadatum"=>{"druid"=>"druid:tv188jw1364", "files"=>[{"uri"=>"file:///dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", "md5"=>"d39b57350974ff87bb96a0cee6fd97bc"}, {"uri"=>"file:///dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", "md5"=>"7bada0347599b6ef6fed075608670b1a"}], "lane-id"=>"default", "basepath"=>"/dor/workspace/tv/188/jw/1364/tv188jw1364/content"}}
production.log-20240223.gz:I, [2024-02-22T13:42:46.931735 #1847829]  INFO -- : [9dcf6b91-5833-4a73-9ffc-afa194fd54d0] [ActiveJob] Enqueued TechnicalMetadataWorkflowJob (Job ID: b0d25996-0185-40e0-b4ca-7250d3345394) to Sidekiq(default) with arguments: {:druid=>"druid:tv188jw1364", :file_infos=>[#<FileInfo:0x00007f044ed80550 @filepath="/dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", @md5="d39b57350974ff87bb96a0cee6fd97bc", @filename="hopkins_vandevere_census_cards_lovers_point_0001.pdf">, #<FileInfo:0x00007f044edaefe0 @filepath="/dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="7bada0347599b6ef6fed075608670b1a", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}
production.log-20240223.gz:I, [2024-02-22T13:42:46.933502 #1519085]  INFO -- : [ActiveJob] [TechnicalMetadataWorkflowJob] [b0d25996-0185-40e0-b4ca-7250d3345394] Performing TechnicalMetadataWorkflowJob (Job ID: b0d25996-0185-40e0-b4ca-7250d3345394) from Sidekiq(default) enqueued at 2024-02-22T21:42:46Z with arguments: {:druid=>"druid:tv188jw1364", :file_infos=>[#<FileInfo:0x00007f2f94df5690 @filepath="/dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.pdf", @md5="d39b57350974ff87bb96a0cee6fd97bc", @filename="hopkins_vandevere_census_cards_lovers_point_0001.pdf">, #<FileInfo:0x00007f2f94df5618 @filepath="/dor/workspace/tv/188/jw/1364/tv188jw1364/content/hopkins_vandevere_census_cards_lovers_point_0001.tif", @md5="7bada0347599b6ef6fed075608670b1a", @filename="hopkins_vandevere_census_cards_lovers_point_0001.tif">], :force=>false}
```

**Comment by jmartin-sul** [comment]
unassigned myself, as i didn't get to this last week (was mostly focused on https://github.com/sul-dlss/preservation_robots/issues/540, and https://github.com/sul-dlss/gis-robot-suite/issues/827 before that)

**Comment by lwrubel** [comment]
I reverted [the common-accessioning code](https://github.com/sul-dlss/common-accessioning/pull/1120/files) that I think was causing the situation that is to be resolved in part 1. Now there aren't unintended deletes of techmd `DroFile` records occurring. However, I can't replicate the issue that the code was trying to resolve, as described in https://github.com/sul-dlss/technical-metadata-service/issues/485. @andrewjbtw could you help me understand how to create the duplicate file situation? I've created an object where there are duplicate files (same file, different names) but haven't been able to cause any errors.

**Comment by andrewjbtw** [comment]
What object are you using? It also may not be possible to recreate this issue with a new item. It might only apply to how we did the retrospective tech MD (which is most of the techMD we have).

**Comment by andrewjbtw** [comment]
I looked for an example in the prod set of druids mentioned in that earlier ticket but the bug we're trying to resolve has wiped out the data that used to be there.

**Comment by lwrubel** [comment]
@justinlittman and I talked this through, and he understood the situation you were describing. It does sound like something that would only apply to objects affected by the retrospective tech MD. Current objects, once the PR above reverts a recent-ish code change, will not have their tech MD deleted in the case where the file is not in the workspace. I've been able to test that and with @ndushay's improvement to the integration test. 

@justinlittman has some thoughts about how to do an audit of tech MD to determine which objects may be affected and is writing up what would be involved in that.

**Comment by lwrubel** [comment]
With #515 describing work to audit tech md (a precursor to any remediation), can this specific ticket be closed, @andrewjbtw?

**Comment by andrewjbtw** [comment]
I think we can close this. #485 will be a problem again but if an audit identifies those druids and then regeneration fills in the gap, that should address it.

In the meantime, I've filed #517 for remediation of a known set of druids that I've identified as missing techMD that I would expect to see.
