### ISSUE TITLE
Properties to extract for A/V formats

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#59]
A/V formats generally consist of a container and then streams or tracks within the container. We should extract technical metadata at both levels: container and stream. 

The characteristics of each stream has an impact on player compatibility, with some playback and editing applications supporting only a limited subset of stream types within a given container. So you might find VLC plays almost any MOV file, but another player only plays MOV files with a particular codec, chroma subsampling, number of audio tracks, etc.

The set of fields listed here is based largely on the properties Stanford's media lab currently extracts on their own, prior to accessioning (listed [here](https://docs.google.com/spreadsheets/d/12W5aqE68xZh5SW7Vzr04uzR8-rMKE3r4_UR7M-RTXCo/edit#gid=1513550010)). I've updated that list with what I think are the current mediainfo field names for the same properties, plus added a small number of additional fields based on my own experience with digital A/V preservation.

For the container (mediainfo calls this track "General"):

```
"@type": "General"
"VideoCount": 
"AudioCount":
"TextCount":
"OtherCount":
"FileExtension": 
"Format": 
"Format_Profile": 
"CodecID": 
"Duration": 
"FrameRate": 
"Encoded_Date": 
```

For video streams:

```
"@type": "Video"
"StreamOrder":
"ID":
"Format":
"Format_Profile":
"CodecID":
"Width":
"Height":
"DisplayAspectRatio":
"PixelAspectRatio:
"FrameRate":
"ColorSpace":
"ChromaSubsampling":
"BitDepth":
"Language":
"StreamSize":
"Standard":
```

For audio streams:

```
"@type": "Audio"
"StreamOrder":
"ID":
"Format":
"Format_Profile":
"CodecID":
"Channels":
"SamplingRate":
"BitDepth":
"StreamSize":
```

For text streams (generally captions or subtitles):

```
"@type": "Text",
"StreamOrder":
"ID":
"Format":
```

For other streams ("other" is a defined type, often turns out to be a timecode track):

```
"@type": "Other",
"StreamOrder":
"ID":
"Type":
Format":
"Title":
```

Notes

- To get a list of all fields that mediainfo could potentially extract if they exist in a given file, run 
```mediainfo --Info-parameters```
- To get a list of all the properties (not just the default output) mediainfo can extract for a specific file in JSON format, run
```mediainfo -f --Output=JSON [file]```
- It's also possible to request specific properties by passing in a configuration file. Syntax for this can be a bit tricky. See the help available with
```mediainfo --help-output```
- Not all stream types or properties we want will exist in a given file

**Comment by justinlittman** [comment]
@andrewjbtw Can you point to or create a **small** example of a container(s) that contain a video, audio, text, and other track for testing/development?

**Comment by andrewjbtw** [comment]
I will track down some samples. If only I could search the techMD for existing items in the repository ...

**Comment by justinlittman** [comment]
@andrewjbtw What mimetypes should run through mediainfo? `video/*` and `audio/*`?

**Comment by andrewjbtw** [comment]
Yes to those. I'll check to see if there's any others but I think that probably covers it.

**Comment by andrewjbtw** [comment]
I've started putting samples in the staging environment at:

```/dor/staging/techmd-samples```

There's currently a small video with multiple streams in the ```audio-video``` folder.
