### ISSUE TITLE
Choose method to map file identification result to technical metadata format choice

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#60]
Two main options:

1\. Work off of mimetype
- items without mimetype will get only general file metadata
  
2\. Map specific pronom IDs to format groups
- items with no ID will get only general file metadata

It comes down to:
- implementation effort
- whether there are formats without mimetypes that we know should get format specific metadata

**Comment by andrewjbtw** [comment]
One approach would be start by using mimetype and then revise if we see things getting missed.

I don't have a good sense of what types of files don't have mimetypes but would meet our format specs. Most of the files without mimetypes I'm familiar with are from "historic" software I saw in my last job's collection.

**Comment by justinlittman** [comment]
That approach makes sense to me. I suspect that having to map the pronom ids would be a headache and error-prone.

**Comment by justinlittman** [comment]
This is the approach currently being used, so closing this ticket.
