### ISSUE TITLE
Properties to extract for PDFs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#64]
The following properties (when present) can be extracted with pdfinfo:

```
PDF version (may already be covered in Siegfried output)
Pages (page count)
Page size
Producer
Creator
Tagged PDF (yes/no)
Encrypted (yes/no)
JavaScript (yes/no)
Form (yes/no)
```

I would also like to record whether a PDF is text-searchable. This is trickier because there doesn't seem to be a metadata flag that says "searchable" or "contains text." Instead, you have to detect it from other metadata.

Possible strategies to detect text:

1. Run pdffonts to see if any fonts are present in the PDF. If there are fonts, that's a sign there is text rather than just images.

2. Run pdftotext and check if there is any text present. You can run ```pdftotext -``` to send the output to stdout rather than create a text file (the default behavior). You could then grep the output for text characters.

I believe both pdffonts and pdftotext are installed along with pdfinfo when installing poppler-utils -- see #65

**Comment by jcoyne** [comment]
Waiting for puppet to  install poppler.
