### ISSUE TITLE
Install mediainfo on techmd servers

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#72]
https://mediaarea.net/en/MediaInfo

**Comment by rsmith11** [comment]
Sorry.  I installed the package we had in our repos, but I now see that's it's a really old package that for unknown reasons was built back in the RHEL 5 days.  I'll get the newer package mirrored from EPEL and get that one installed on those systems.

**Comment by rsmith11** [comment]
Latest package, 19.09, installed on techmd servers.

**Comment by justinlittman** [comment]
Works for me. Thanks!
