### ISSUE TITLE
Mount preservation storage on techmd servers

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#73]
Mount preservation storage roots on techmd servers **READ-ONLY** to allow for reprocessing files.

The preservation storage roots should be the correct storage roots for that environment. (That is, the stage preservation storage roots should be mounted on the stage techmd server.)

This approach was OKed by @julianmorley.

**Comment by rsmith11** [comment]
For my own clarification, on the prod techmd system it should be all the service-disk mounts (1-22), and on the stage/qa servers it should be the one `services-disk-stage` mount?  I also see an `/sdr-transfers` mount on some of them, but that one is read-write where-ever mounted.

**Comment by jcoyne** [comment]
@rsmith11 yes all 1-22 on the services-disk-stage mount.   /sdr-transfers is used when we send data to preservation, but this service only needs to read from preservation, so read-only.

**Comment by rsmith11** [comment]
I have a storage request put in to make those mounts accessible to the techmd systems.  When that work is completed, I can mount them.

**Comment by rsmith11** [comment]
Storage request went through.  Service disks should be loaded on appropriate techmd systems.
